# Generated by Django 4.1.3 on 2022-12-15 03:44

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True, verbose_name='Correo')),
                ('tipo_documento', models.CharField(choices=[('cedula', 'Cedula'), ('pasaporte', 'Pasaporte')], max_length=20, verbose_name='Tipo de documento')),
                ('cedula', models.CharField(blank=True, max_length=13, null=True, verbose_name='Cedula')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('celular', models.CharField(blank=True, max_length=13, null=True, verbose_name='N.Celular')),
                ('direccion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Direccion')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha_nacimiento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Fotos_usuarios/', verbose_name='Subir una foto')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_emprendimiento', models.CharField(max_length=150, verbose_name='Categoria')),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_categorías/', verbose_name='Foto categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_Serv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=150, verbose_name='Tipo de Servicio')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_emprendimiento', models.CharField(max_length=150, verbose_name='Emprendimiento')),
                ('direccion', models.CharField(max_length=150, verbose_name='direccion')),
                ('celular', models.CharField(max_length=13, verbose_name='Celular')),
                ('tel_fijo', models.CharField(max_length=13, verbose_name='Telf.Fijo')),
                ('descripcion', models.TextField()),
                ('hora_apertura', models.DateTimeField()),
                ('hora_cierre', models.DateTimeField()),
                ('altitud', models.CharField(max_length=20, verbose_name='altitud')),
                ('latitud', models.CharField(max_length=20, verbose_name='latitud')),
                ('fotoemp', models.ImageField(blank=True, null=True, upload_to='fotos_emprendimiento/', verbose_name='Subir una foto')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Video Promocional')),
                ('face', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('titter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('categorias_emprendimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.categoria_emp', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prod', models.CharField(max_length=150, verbose_name='Nombre producto')),
                ('descripcion', models.TextField()),
                ('Precio', models.FloatField(verbose_name='Precio')),
                ('fecha_elaboracion', models.DateField(blank=True, null=True)),
                ('fecha_caducidad', models.DateField(null=True)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('foto_prod', models.ImageField(blank=True, upload_to='Fotos_producto/', verbose_name='Subir una foto')),
                ('tipo_emprendimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.emprendimiento', verbose_name='Emprendimiento_tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('administracion.persona',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pais_origen', models.CharField(max_length=13, verbose_name='País de Origen')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('administracion.persona',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(verbose_name='Calificación')),
                ('comerntario_sugerencia', models.TextField(verbose_name='Comentarios y Sugerencias')),
                ('categoriaserv', models.ManyToManyField(blank=True, to='administracion.categoria_serv')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cedula')),
                ('nombres', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('tipo_emprendimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.emprendimiento', verbose_name='Emprendimiento_tipo')),
                ('tipo_producto', models.ManyToManyField(blank=True, related_name='producto', to='administracion.producto')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Fotos_usuarios/', verbose_name='Subir una foto')),
                ('videog', models.URLField(blank=True, null=True, verbose_name='Video Promocional')),
                ('galerias', models.ManyToManyField(blank=True, to='administracion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('subtotal', models.IntegerField(verbose_name='Subtotal')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('productos', models.ManyToManyField(blank=True, to='administracion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Emprendedor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('emprendimientos', models.ManyToManyField(blank=True, to='administracion.emprendimiento')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('administracion.persona',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
